version: "3.9"

services:
  frontend:
    image: YOUR_DOCKERHUB/frontend:latest
    restart: always

  backend:
    image: YOUR_DOCKERHUB/backend:latest
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend